//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 17.04.2019 23:55:48
namespace WebAPI.Models
{
    /// <summary>
    /// There are no comments for ProductSingle in the schema.
    /// </summary>
    public partial class ProductSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Product>
    {
        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Product> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Product : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="cena2015">Initial value of Cena2015.</param>
        /// <param name="prodano2015">Initial value of Prodano2015.</param>
        /// <param name="cena2016">Initial value of Cena2016.</param>
        /// <param name="prodano2016">Initial value of Prodano2016.</param>
        /// <param name="cena2017">Initial value of Cena2017.</param>
        /// <param name="prodano2017">Initial value of Prodano2017.</param>
        /// <param name="cena2018">Initial value of Cena2018.</param>
        /// <param name="prodano2018">Initial value of Prodano2018.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Product CreateProduct(int ID, 
                    int cena2015, 
                    int prodano2015, 
                    int cena2016, 
                    int prodano2016, 
                    int cena2017, 
                    int prodano2017, 
                    int cena2018, 
                    int prodano2018)
        {
            Product product = new Product();
            product.Id = ID;
            product.Cena2015 = cena2015;
            product.Prodano2015 = prodano2015;
            product.Cena2016 = cena2016;
            product.Prodano2016 = prodano2016;
            product.Cena2017 = cena2017;
            product.Prodano2017 = prodano2017;
            product.Cena2018 = cena2018;
            product.Prodano2018 = prodano2018;
            return product;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Cena2015 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Cena2015
        {
            get
            {
                return this._Cena2015;
            }
            set
            {
                this.OnCena2015Changing(value);
                this._Cena2015 = value;
                this.OnCena2015Changed();
                this.OnPropertyChanged("Cena2015");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Cena2015;
        partial void OnCena2015Changing(int value);
        partial void OnCena2015Changed();
        /// <summary>
        /// There are no comments for Property Prodano2015 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Prodano2015
        {
            get
            {
                return this._Prodano2015;
            }
            set
            {
                this.OnProdano2015Changing(value);
                this._Prodano2015 = value;
                this.OnProdano2015Changed();
                this.OnPropertyChanged("Prodano2015");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Prodano2015;
        partial void OnProdano2015Changing(int value);
        partial void OnProdano2015Changed();
        /// <summary>
        /// There are no comments for Property Cena2016 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Cena2016
        {
            get
            {
                return this._Cena2016;
            }
            set
            {
                this.OnCena2016Changing(value);
                this._Cena2016 = value;
                this.OnCena2016Changed();
                this.OnPropertyChanged("Cena2016");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Cena2016;
        partial void OnCena2016Changing(int value);
        partial void OnCena2016Changed();
        /// <summary>
        /// There are no comments for Property Prodano2016 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Prodano2016
        {
            get
            {
                return this._Prodano2016;
            }
            set
            {
                this.OnProdano2016Changing(value);
                this._Prodano2016 = value;
                this.OnProdano2016Changed();
                this.OnPropertyChanged("Prodano2016");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Prodano2016;
        partial void OnProdano2016Changing(int value);
        partial void OnProdano2016Changed();
        /// <summary>
        /// There are no comments for Property Cena2017 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Cena2017
        {
            get
            {
                return this._Cena2017;
            }
            set
            {
                this.OnCena2017Changing(value);
                this._Cena2017 = value;
                this.OnCena2017Changed();
                this.OnPropertyChanged("Cena2017");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Cena2017;
        partial void OnCena2017Changing(int value);
        partial void OnCena2017Changed();
        /// <summary>
        /// There are no comments for Property Prodano2017 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Prodano2017
        {
            get
            {
                return this._Prodano2017;
            }
            set
            {
                this.OnProdano2017Changing(value);
                this._Prodano2017 = value;
                this.OnProdano2017Changed();
                this.OnPropertyChanged("Prodano2017");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Prodano2017;
        partial void OnProdano2017Changing(int value);
        partial void OnProdano2017Changed();
        /// <summary>
        /// There are no comments for Property Cena2018 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Cena2018
        {
            get
            {
                return this._Cena2018;
            }
            set
            {
                this.OnCena2018Changing(value);
                this._Cena2018 = value;
                this.OnCena2018Changed();
                this.OnPropertyChanged("Cena2018");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Cena2018;
        partial void OnCena2018Changing(int value);
        partial void OnCena2018Changed();
        /// <summary>
        /// There are no comments for Property Prodano2018 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Prodano2018
        {
            get
            {
                return this._Prodano2018;
            }
            set
            {
                this.OnProdano2018Changing(value);
                this._Prodano2018 = value;
                this.OnProdano2018Changed();
                this.OnPropertyChanged("Prodano2018");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Prodano2018;
        partial void OnProdano2018Changing(int value);
        partial void OnProdano2018Changed();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::WebAPI.Models.Product as global::WebAPI.Models.ProductSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebAPI.Models.ProductSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebAPI.Models.Product> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebAPI.Models.ProductSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebAPI.Models.Product as global::WebAPI.Models.ProductSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::WebAPI.Models.ProductSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebAPI.Models.Product> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::WebAPI.Models.ProductSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebAPI.Models.Product> Product
        {
            get
            {
                if ((this._Product == null))
                {
                    this._Product = base.CreateQuery<global::WebAPI.Models.Product>("Product");
                }
                return this._Product;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebAPI.Models.Product> _Product;
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToProduct(global::WebAPI.Models.Product product)
        {
            base.AddObject("Product", product);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""WebAPI.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Product"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Cena2015"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Prodano2015"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Cena2016"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Prodano2016"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Cena2017"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Prodano2017"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Cena2018"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Prodano2018"" Type=""Edm.Int32"" Nullable=""false"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Product"" EntityType=""WebAPI.Models.Product"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.CsdlReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
