using System;

namespace Database
{
    public class Student : IComparable<Student>
    {
        public string OsCislo { get; set; }
        public string Jmeno { get; set; }
        public string Prijmeni { get; set; }
        public string UserName { get; set; }
        public int Rocnik { get; set; }
        public string OborKomb { get; set; }

        public int CompareTo(Student other)
        {
            return this.Prijmeni.CompareTo(other.Prijmeni);
        }

        public override string ToString()
        {
            return $"{OsCislo}, {Jmeno}, {Prijmeni}, {UserName}, {Rocnik}, {OborKomb}";
        }
    }

    public class ReadonlyDB
    {
        public static Student[] Students = {
	    new Student() {OsCislo="R17700",
			   Jmeno="Daniel", 
			   Prijmeni="BAZALA",
			   UserName="bazada00",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17484",
			   Jmeno="Michal", 
			   Prijmeni="BEZDĚK",
			   UserName="bezdmi01",
			   Rocnik=2,
			   OborKomb="INF"},
	    new Student() {OsCislo="R17703",
			   Jmeno="Petr", 
			   Prijmeni="BOBEK",
			   UserName="bobepe00",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R16821",
			   Jmeno="David", 
			   Prijmeni="DOBRÝ",
			   UserName="dobrda00",
			   Rocnik=3,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17710",
			   Jmeno="Eliška", 
			   Prijmeni="FOLTASOVÁ",
			   UserName="foltel02",
			   Rocnik=2,
			   OborKomb="APLINF"},
                new Student() {OsCislo="R17710",
               Jmeno="Eliška",
               Prijmeni="FOLTASOVÁ",
               UserName="foltel02",
               Rocnik=2,
               OborKomb="APLINF"},
        new Student() {OsCislo="R17711",
			   Jmeno="Dominika", 
			   Prijmeni="GAJDOVÁ",
			   UserName="gajddo00",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17485",
			   Jmeno="Martin", 
			   Prijmeni="HAMPEL",
			   UserName="hampma02",
			   Rocnik=2,
			   OborKomb="INF"},
	    new Student() {OsCislo="R17713",
			   Jmeno="Ivo", 
			   Prijmeni="HORÁK",
			   UserName="horaiv10",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    
	    new Student() {OsCislo="R16844",
			   Jmeno="Lukáš", 
			   Prijmeni="JAWOREK",
			   UserName="jawolu00",
			   Rocnik=3,
			   OborKomb="APLINF"},
        new Student() {OsCislo="R17717",
               Jmeno="Petr",
               Prijmeni="JANIŠ",
               UserName="janipe05",
               Rocnik=2,
               OborKomb="APLINF"},
        new Student() {OsCislo="R17720",
			   Jmeno="Aleš", 
			   Prijmeni="KAŠPÁREK",
			   UserName="kaspal00",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17721",
			   Jmeno="Jakub", 
			   Prijmeni="KATZER",
			   UserName="katzerj",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R18570",
			   Jmeno="Matěj", 
			   Prijmeni="KOLÁŘ",
			   UserName="kolama22",
			   Rocnik=1,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R18582",
			   Jmeno="Veronika", 
			   Prijmeni="MENDEOVÁ",
			   UserName="mendve00",
			   Rocnik=1,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17736",
			   Jmeno="Jan", 
			   Prijmeni="NEJEZCHLEBA",
			   UserName="nejeja01",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R16869",
			   Jmeno="Jan", 
			   Prijmeni="NERUŠIL",
			   UserName="neruja01",
			   Rocnik=3,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17740",
			   Jmeno="Martin", 
			   Prijmeni="PIFKA",
			   UserName="pifkma00",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17745",
			   Jmeno="Vít", 
			   Prijmeni="ŘEHÁK",
			   UserName="rehavi",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17746",
			   Jmeno="Marek", 
			   Prijmeni="SCHILLER",
			   UserName="schima07",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R18600",
			   Jmeno="Václav", 
			   Prijmeni="STEZKA",
			   UserName="stezva00",
			   Rocnik=1,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R16917",
			   Jmeno="Alena", 
			   Prijmeni="SVOBODOVÁ",
			   UserName="svobal06",Rocnik=3,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R16894",
			   Jmeno="Martin", 
			   Prijmeni="ŠABAT",
			   UserName="sabama01",
			   Rocnik=3,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17752",
			   Jmeno="Ivo", 
			   Prijmeni="ŠMEREK",
			   UserName="smeriv00",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17756",
			   Jmeno="Michal", 
			   Prijmeni="ŠUSTERA",
			   UserName="sustmi01",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17757",
			   Jmeno="Petr", 
			   Prijmeni="UNZEITIG",
			   UserName="unzepe01",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17758",
			   Jmeno="Martin", 
			   Prijmeni="URBANEC",
			   UserName="urbama10",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17759",
			   Jmeno="Jakub", 
			   Prijmeni="VEČEŘA",
			   UserName="veceja05",
			   Rocnik=2,
			   OborKomb="APLINF"},
	    new Student() {OsCislo="R17499",
			   Jmeno="Vojtěch", 
			   Prijmeni="ŽÁČEK",
			   UserName="zacevo00",
			   Rocnik=2,
			   OborKomb="INF"}

	};
    }
}

